project:
  type: website
  output-dir: docs

  render:
    # Render all .qmd files
    - "**/*.qmd"
    # Exclude specific directories
    - "!zzz_old/"

  #   # Don't render anything in the manuscript folder because otherwise all the
  #   # output gets placed in _site/ only, which is annoying. Instead this folder
  #   # needs to be rendered separately, and *before* the overall website project
  #   # (which is doable since this whole build process is orchestrated by targets)
  #   - "!manuscript/"
  #
  # resources:
  #   # But *do* place the outputs from the manuscript in the rendered site folder
  #   - "manuscript/output/"

execute:
  freeze: auto  # Re-render only when source changes


website:
  title: "Template Quarto Website"
  site-url: "https://lulliter.github.io/template/"
  repo-url: "https://github.com/Lulliter/template"
  repo-actions: [edit, issue]

  page-navigation: true

  navbar:
    pinned: true
    background: "#033c55"
    search: true
    left:
      - text: "Home"
        icon: house-fill # https://icons.getbootstrap.com/?q=home
        file: index.qmd
      - text: "Data"
        file: exploration/data-prep.qmd
      - text: "Analysis"
        file: exploration/hypotheses.qmd
      - text: "Presentations"
        file: presentations/index.qmd
      - text: "Paper"
        menu:
          - file: exploration/paper.qmd

    right:
      - icon: github
        aria-label: github
        href: https://github.com/Lulliter/template

  sidebar:
    - title: "Data"
      style: docked
      background: "#005d82"
      contents:
        - section: "Data"
          contents:
            - exploration/data-prep.qmd
            - exploration/data-final.qmd
    - title: "Analysis"
      contents:
        - section: "Research Questions"
          contents:
            - exploration/hypotheses.qmd
        - section: "Models"
          contents:
            - exploration/model-details.qmd
#
#     - title: "Empty space lol"

  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} 2025 by Luisa M. Mimmi<br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub](https://github.com/andrewheiss/zany-zebra)

format:
  html:
    theme:
      - zephyr
      - assets/custom.scss
    toc: true
    toc-location: right
    code-fold: true
    code-tools: true
    highlight-style: monokai

language:
  title-block-published: "Date"

# --- Default options for tbl and fig captions location (top)
fig-cap-location: top
tbl-cap-location: top



# --- Important bc Pandocâ€™s default resource-path is the directory of each input file
## Let pages see files in the project root (.) and the bib folder explicitly
# resource-path: [".", "bib"]
# bibliography: bib/CRP_dash.bib
bibliography: manuscript/bib/CARIPARMA.bib
csl: manuscript/bib/chicago-shortened-notes-bibliography.csl