project:
  title: "Manuscript"
  output-dir: output

  render:
    - "manuscript.qmd"

# This is necessary to keep intermediate files/folders hanging around when
# rendering to the same output format (like two different PDFs)
# https://github.com/quarto-dev/quarto-cli/issues/8373#issuecomment-1979245883
keep-md: false

format:
# Nice HTML output
  html:
    toc: true
    number-sections: true
# Nice PDF output
  pdf:
    toc: true
    number-sections: true
# Nice Word output
  docx:
    toc: true
    reference-doc: "assets/custom-reference-doc.docx"


# REference on why use Quarto to make Microsoft Office docs: [linkedin](https://www.linkedin.com/learning/data-science-reporting-with-quarto-for-python/why-use-quarto-to-make-microsoft-office-docs?resume=false)

